### ISSUE TITLE
[TRANSLATION] Course CYP201 - FR

### ISSUE THREAD

**Issue by LoicPandul** [DecouvreBitcoin/sovereign-university-data#1244]
PBN version: https://planb.network/courses/cyp201
EN GitHub version: https://github.com/PlanB-Network/bitcoin-educational-content/blob/dev/courses/cyp201/en.md
FR GitHub version: https://github.com/PlanB-Network/bitcoin-educational-content/blob/dev/courses/cyp201/fr.md

**Comment by tutoriel-pandul** [comment]
working on it

**Comment by LoicPandul** [comment]
Fake issue created to take screenshots as part of making a contribution tutorial for PBN.
