### ISSUE TITLE
Translation of website elements

### ISSUE THREAD

**Issue by Rogzy-DB** [DecouvreBitcoin/sovereign-university-data#148]
PlanB.network front also need to be translated. We are using Crowdin for this.

The text being translated is primarily the main content of the platform, such as buttons, headers, footers, static titles, etc...

You will have to create an account on crowdin.
The corresponding project is [here](https://crowdin.com/editor/the-sovereign-academy/30/en-fr?view=comfortable&filter=basic&value=0)

**Comment by Asi0Flammeus** [comment]
done by myself.
