### ISSUE TITLE
Translate main text of footer, home page, menu

### ISSUE THREAD

**Issue by Rogzy-DB** [DecouvreBitcoin/sovereign-university-data#149]
The new version of the university requires a thorough review. We are using Crowdin for this. The text being translated is primarily the main content of the platform, such as buttons, headers, footers, static titles, etc."

https://crowdin.com/project/the-sovereign-academy/ja

**Comment by yutaro21jp** [comment]
All done! (100%)

**Comment by Asi0Flammeus** [comment]
Thanks for your contribution 🧡
