### ISSUE TITLE
Translate main website information (home page, menu, etc)

### ISSUE THREAD

**Issue by Rogzy-DB** [DecouvreBitcoin/sovereign-university-data#153]
The new version of the university requires a thorough review. We are using Crowdin for this. The text being translated is primarily the main content of the platform, such as buttons, headers, footers, static titles, etc.

https://crowdin.com/project/the-sovereign-academy/pt-PT

**Comment by TatiMeditaction** [comment]
Hi @Rogzy-DB  :) I've just finished this one. Could you check if everything is OK?

**Comment by Asi0Flammeus** [comment]
Yes everything's seems okay!
Thank you for this work 🧡
