### ISSUE TITLE
SECU 101 - Update your Online Security

### ISSUE THREAD

**Issue by Rogzy-DB** [DecouvreBitcoin/sovereign-university-data#16]

**Comment by Asi0Flammeus** [comment]
The first review was merged in #19. 
It still misses the review from Renaud (Course author).

**Comment by Asi0Flammeus** [comment]
- [ ] Video translation needed in EN (would be quite hard) 
- [ ] for v2: shoot the tutorial part and link it in the course

**Comment by Asi0Flammeus** [comment]
As the course is complete in french, I will close the issue until a v2 is needed
