### ISSUE TITLE
Arabic - Tutorial Node

### ISSUE THREAD

**Issue by Rogzy-DB** [DecouvreBitcoin/sovereign-university-data#50]
Translation of the Tutorial, node page: https://sovereignuniversity.org/tutorials/node

## List of tutorial: 

- [ ] Linux ;  https://github.com/DecouvreBitcoin/sovereign-university-data/blob/Add-Arabic-Language/tutorials/node/bitcoin-core-linux/bitcoin%20core%20linuxfr_Arabic.md
- [ ] Windows ; https://github.com/DecouvreBitcoin/sovereign-university-data/blob/Add-Arabic-Language/tutorials/node/bitcoin-core-mac-windows/bitcoin%20core%20windows_Arabic.md
- [ ] Lapp ; https://github.com/DecouvreBitcoin/sovereign-university-data/blob/Add-Arabic-Language/tutorials/node/lapp/lappen_Arabic.md
- [ ]  My node : https://github.com/DecouvreBitcoin/sovereign-university-data/blob/Add-Arabic-Language/tutorials/node/mynode/my%20nodeen_Arabic.md
- [ ] Nutrino: https://github.com/DecouvreBitcoin/sovereign-university-data/blob/Add-Arabic-Language/tutorials/node/neutrino/nutrinoen_Arabic.md
- [ ] Raspiblitz ; https://github.com/DecouvreBitcoin/sovereign-university-data/blob/Add-Arabic-Language/tutorials/node/raspiblitz/raspiblitz%20en_Arabic.md
- [ ]  RGB : https://github.com/DecouvreBitcoin/sovereign-university-data/blob/Add-Arabic-Language/tutorials/node/rgb/rgb%20fr_Arabic.md
- [ ] Ronin Dojo : https://github.com/DecouvreBitcoin/sovereign-university-data/blob/Add-Arabic-Language/tutorials/node/ronin-dojo/ronin%20dojo_Arabic.md
- [ ] Start 9 - https://github.com/DecouvreBitcoin/sovereign-university-data/blob/Add-Arabic-Language/tutorials/node/start9/start%209en_Arabic.md
- [ ] What tower : https://github.com/DecouvreBitcoin/sovereign-university-data/blob/Add-Arabic-Language/tutorials/node/watch-tower/watch%20tower_Arabic.md

Commit for each changes

**Comment by Asi0Flammeus** [comment]
will close this issue as the system to manage proofreading content issue has now changed. (1 issue per content per language)
