### ISSUE TITLE
ECO 102 - Frédéric Bastiat, Life, Influences and Economic Thought

### ISSUE THREAD

**Issue by Asi0Flammeus** [DecouvreBitcoin/sovereign-university-data#523]
Course about the economist F. Bastiat

- sources:
  -  https://fredericbastiat.fr/un-cours-complet-en-video1
  - https://www.youtube.com/playlist?list=PLHMqffn5cyaCP7VfJR-n_ECoD0VBz146U

**Comment by Rogzy-DB** [comment]
Images files upgraded: 
- HD images
- legend 
- remove pointless images

**Comment by Asi0Flammeus** [comment]
index: change it to level 200, like 206 
title: Bastiat Economical Influence
 - in FR: Influence Economique de Bastiat
description: shorten it  
- videos: will be one of the first, as the pptx videos should be ready in following days
- images: some have been deleted so md needs to be updated

**Comment by Asi0Flammeus** [comment]
- [x] ECO 203 new index
- [x] new name - Bastiat Economic Thought
- [x] shorten description
