### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by pythcoiner** [DecouvreBitcoin/sovereign-university-data#6]
These links are broken:
![image](https://github.com/DecouvreBitcoin/sovereign-university-data/assets/124568858/926cd4af-acac-4f32-b8f4-74215a99a97c)
[https://sovereignuniversity.org/course/btc101](https://sovereignuniversity.org/course/btc101)

**Comment by Asi0Flammeus** [comment]
wrong repo but already fixed
