### ISSUE TITLE
[TRANSLATION] btc305 - zh-Hans

### ISSUE THREAD

**Issue by MariJJhodl** [DecouvreBitcoin/sovereign-university-data#605]
en PBN version: https://planb.network/en/courses/btc305
en github version: https://github.com/PlanB-Network/bitcoin-educational-content/blob/dev/courses/btc305/en.md
zh-hans github version: https://github.com/PlanB-Network/bitcoin-educational-content/tree/dev/courses/btc305

**Comment by MilankovicProtocol** [comment]
Working on it

**Comment by MilankovicProtocol** [comment]
Completed
