### ISSUE TITLE
[PROOFREADING] add-new-language-weblate - nb-no

### ISSUE THREAD

**Issue by MariJJhodl** [DecouvreBitcoin/sovereign-university-data#626]
Weblate link: https://weblate.planb.network/projects/planb-network-website/website-elements/nb_NO/

**Comment by MariJJhodl** [comment]
Proofread process for the website in Norwegian-Bokmål
https://weblate.planb.network/projects/planb-network-website/website-elements/nb_NO/
https://weblate.planb.network/projects/planb-network-website/website-elements/nn/
Assigned to: Rtbit

**Comment by rtbit** [comment]
Hello! I am 100% finished with the Norwegian Bokmål. (nb_NO) translation on Weblate.
https://weblate.planb.network/projects/planb-network-website/website-elements/nb_NO/
