### ISSUE TITLE
[TRANSLATION] btc304 - zh-Hans

### ISSUE THREAD

**Issue by MariJJhodl** [DecouvreBitcoin/sovereign-university-data#635]
en PBN version: https://planb.network/en/courses/btc302
en github version: https://github.com/PlanB-Network/bitcoin-educational-content/blob/dev/courses/btc302/en.md
zh-hans github version: https://github.com/PlanB-Network/bitcoin-educational-content/blob/dev/courses/btc302/zh-Hans.md

**Comment by MilankovicProtocol** [comment]
Working on it

**Comment by MilankovicProtocol** [comment]
Completed
