### ISSUE TITLE
[PROOFREADING] add-new-language-weblate - de

### ISSUE THREAD

**Issue by MariJJhodl** [DecouvreBitcoin/sovereign-university-data#648]
Proofreading of website strings in German

**Comment by MariJJhodl** [comment]
First proofreading of the weblate (https://weblate.planb.network/projects/planb-network-website/website-elements/de/) being done by AleAigo

**Comment by AlessiaAigo** [comment]
First German proofreading of the weblate completed.

**Comment by ghub-user-180** [comment]
German weblate translation started
