### ISSUE TITLE
[INFO] Pregunta

### ISSUE THREAD

**Issue by ArOs-47** [DecouvreBitcoin/sovereign-university-data#673]
Hola a todos,

He encontrado un bot de Telegram llamado [BLURRY], con nombre de usuario en [BLURRY], que supuestamente permite ganar Hash, con la cual se pueden cambiar por Bitcoin a través de clics diarios . Me gustaría saber si alguien ha tenido experiencia con este bot y puede confirmar su autenticidad.

¡Gracias de antemano por su ayuda! Y mil disculpas por colocar mi asunto en este otro asunto.

**Comment by BitPreto** [comment]
I obfuscated telegram link you mentioned, to avoid promoting external ads on the repository!

**Comment by BitPreto** [comment]
If you go looking in the main page of the repository you will find a readme file with all information how to start contributing, there you'll find also a telegram group link that we use to coordinate contribution efforts

**Comment by ArOs-47** [comment]
I apologize if I caused you any inconvenience, maybe I don't know how to use the GigHub app 100% yet, the question is real, and from all that I read, I did it here since it was the closest thing that I understood to what someone could do answer me, I wish you much success.

**Comment by ArOs-47** [comment]
I apologize if I caused you any inconvenience, maybe I don't know how to use the GigHub app 100% yet, the question is real, and from all that I read, I did it here since it was the closest thing that I understood to what someone could do answer me, I wish you much success.

**Comment by BitPreto** [comment]
Yeah I understand it now, so I'd really like suggesting something as of know:
- in general, be careful of potential scams out there (I am not saying the one thing you asked is, just exercise caution with common sense)
- this repository github stores all data that are going to be published on PlanB Network website, you may take a look over there, in a more user-friendly space, where you may find some answers to some of your questions
- It seems to me you are quite new to the Bitcoin world (if I am wrong please accept my apologies), hence you could take a closer look at beginner courses on the PlanB website, it may be useful
- In any case, if you discover in the future that we are missing bitcoin resources in the website you can always join the telegram group and asks about that particular thing, that place is better suited for informal questions such this :)
