### ISSUE TITLE
[TRANSLATION] btc101 - nb-no

### ISSUE THREAD

**Issue by MariJJhodl** [DecouvreBitcoin/sovereign-university-data#711]
en PBN version: https://planb.network/en/courses/btc101
en github version: https://github.com/PlanB-Network/bitcoin-educational-content/blob/dev/courses/btc101/en.md
nb-no github version: https://github.com/PlanB-Network/bitcoin-educational-content/blob/norwegian-bokm%C3%A5l-initial-upload/courses/btc101/nb-NO.md

**Comment by rtbit** [comment]
Want to translate/proofread this.

**Comment by MariJJhodl** [comment]
First [proofreading](https://github.com/PlanB-Network/bitcoin-educational-content/pull/756) completed by [rtbit](https://github.com/rtbit)
