### ISSUE TITLE
[TRANSLATION] paynym-bip47- it

### ISSUE THREAD

**Issue by MariJJhodl** [DecouvreBitcoin/sovereign-university-data#730]
en PBN version: https://planb.network/en/tutorials/privacy/paynym-bip47
en github version: https://github.com/PlanB-Network/bitcoin-educational-content/blob/dev/tutorials/privacy/paynym-bip47/en.md
it github version: https://github.com/PlanB-Network/bitcoin-educational-content/blob/dev/tutorials/privacy/paynym-bip47
/it.md

**Comment by TinF0ilHat1** [comment]
PR:
https://github.com/PlanB-Network/bitcoin-educational-content/pull/766
