### ISSUE TITLE
[TRANSLATION] remix-whirlpool - it

### ISSUE THREAD

**Issue by MariJJhodl** [DecouvreBitcoin/sovereign-university-data#731]
en PBN version: https://planb.network/en/tutorials/privacy/remix-whirlpool
en github version: https://github.com/PlanB-Network/bitcoin-educational-content/blob/dev/tutorials/privacy/remix-whirlpool/en.md
it github version: https://github.com/PlanB-Network/bitcoin-educational-content/blob/dev/tutorials/privacy/remix-whirlpool/it.md

**Comment by TinF0ilHat1** [comment]
PR:
https://github.com/PlanB-Network/bitcoin-educational-content/pull/766
