### ISSUE TITLE
[TRANSLATION] ricochet - it

### ISSUE THREAD

**Issue by MariJJhodl** [DecouvreBitcoin/sovereign-university-data#732]
en PBN version: https://planb.network/en/tutorials/privacy/richochet
en github version: https://github.com/PlanB-Network/bitcoin-educational-content/blob/dev/tutorials/privacy/richochet/en.md
it github version: https://github.com/PlanB-Network/bitcoin-educational-content/blob/dev/tutorials/privacy/richochet/it.md

**Comment by TinF0ilHat1** [comment]
PR:
https://github.com/PlanB-Network/bitcoin-educational-content/pull/766
