### ISSUE TITLE
[TRANSLATION] utxo-labelling - it

### ISSUE THREAD

**Issue by MariJJhodl** [DecouvreBitcoin/sovereign-university-data#735]
en PBN version: https://planb.network/en/tutorials/privacy/utxo-labelling
en github version: https://github.com/PlanB-Network/bitcoin-educational-content/blob/dev/tutorials/privacy/utxo-labelling/en.md
it github version: https://github.com/PlanB-Network/bitcoin-educational-content/blob/dev/tutorials/privacy/utxo-labelling/it.md

**Comment by TinF0ilHat1** [comment]
PR:
https://github.com/PlanB-Network/bitcoin-educational-content/pull/766
