### ISSUE TITLE
[TRANSLATION] wst-anonsets - it

### ISSUE THREAD

**Issue by MariJJhodl** [DecouvreBitcoin/sovereign-university-data#736]
en PBN version: https://planb.network/en/tutorials/privacy/wst-anonsets
en github version: https://github.com/PlanB-Network/bitcoin-educational-content/blob/dev/tutorials/privacy/wst-anonsets/en.md
it github version: https://github.com/PlanB-Network/bitcoin-educational-content/blob/dev/tutorials/privacy/wst-anonsets/it.md

**Comment by TinF0ilHat1** [comment]
PR:
https://github.com/PlanB-Network/bitcoin-educational-content/pull/766
