### ISSUE TITLE
[TUTORIAL] Alby Hub

### ISSUE THREAD

**Issue by BitPreto** [DecouvreBitcoin/sovereign-university-data#749]
[Video tutorial](https://youtu.be/2Z1BzwxdP4I) from BTC Sessions publish on Sep 12, 2024.

This tutorial walks you through setting up and using Alby Hub - a self custodial lightning node that you can host in the cloud or on your own hardware. This node can be linked with mobile wallets, browser plugins, and your Alby account can also serve as a Nostr key/lightning login mechanism.

**Comment by LoicPandul** [comment]
I’ll start working on it next week. We might split it into different tutorials, as it can mainly be used in three ways: with the paid Alby cloud, as a frontend for another node (Umbrel, Start9...), or as a node directly on the laptop.

**Comment by BitPreto** [comment]
I understand it, I guess the simplest process would be the combo one frontend tuto and paid alby cloud tuto. if you agree too, what would in such case be the first tuto you are going to work on (between the two of them)?

**Comment by LoicPandul** [comment]
Yes, I agree! I’m not sure yet, I’ll check on Tuesday, but I can start with the cloud version if you’d like. ;)

**Comment by LoicPandul** [comment]
I’m working on the tutorial, and I think we’ll end up making just one. The functionality is exactly the same in terms of the interface; only the setup process differs. So, I’ll start with the paid cloud version and might add a few notes at the beginning for those who want to use it locally on a laptop or with Umbrel/Start9.

**Comment by BitPreto** [comment]
Understood :+1: this one you mentioned seems a good solution. Regarding [the old alby tuto](https://planb.network/tutorials/wallet/alby) we could even delete it right now, since it is just a yt video
