### ISSUE TITLE
[TRANSLATION] wallet/blixt - vi

### ISSUE THREAD

**Issue by MariJJhodl** [DecouvreBitcoin/sovereign-university-data#751]
en PBN version: https://planb.network/en/tutorials/wallet/blixt
en github version: https://github.com/PlanB-Network/bitcoin-educational-content/blob/dev/tutorials/wallet/blixt/en.md
vi github version: https://github.com/PlanB-Network/bitcoin-educational-content/blob/dev/tutorials/wallet/blixt/vi.md

**Comment by Henry-Da0** [comment]
Done PR.
