### ISSUE TITLE
[PROOFREADING] phoenix - vi

### ISSUE THREAD

**Issue by MariJJhodl** [DecouvreBitcoin/sovereign-university-data#752]
en PBN version: https://planb.network/en/tutorials/wallet/phoenix
en github version: https://github.com/PlanB-Network/bitcoin-educational-content/blob/dev/tutorials/wallet/phoenix/en.md
vi github version: https://github.com/PlanB-Network/bitcoin-educational-content/blob/dev/tutorials/wallet/phoenix/vi.md

**Comment by Henry-Da0** [comment]
Done PR

**Comment by MariJJhodl** [comment]
Proofreading momentarily on hold
