### ISSUE TITLE
[TRANSLATION] muun - vi

### ISSUE THREAD

**Issue by MariJJhodl** [DecouvreBitcoin/sovereign-university-data#755]
en PBN version: https://planb.network/en/tutorials/wallet/mobile/muun-111b56b0-4872-4130-ad2e-e58f8363451d
en github version: https://github.com/PlanB-Network/bitcoin-educational-content/blob/dev/tutorials/wallet/muun/en.md
vi github version: https://github.com/PlanB-Network/bitcoin-educational-content/blob/dev/tutorials/wallet/muun/vi.md

**Comment by Henry-Da0** [comment]
Done PR!
