### ISSUE TITLE
[TUTORIAL] Ledger Nano S

### ISSUE THREAD

**Issue by BitPreto** [DecouvreBitcoin/sovereign-university-data#823]
Link existing tutorial to new created issue

**Comment by LoicPandul** [comment]
This tutorial is clearly outdated, but I suggest not updating it, because it’s pointless to spend time on it because this HW will no longer receive any updates from LEdger (end of support). So we can still keep the tutorial for a few months, then we’ll archive it I think. I have a reminder

**Comment by LoicPandul** [comment]
Tutorial removed from the repo and archived in PR #4122
