### ISSUE TITLE
[TUTORIAL] GnuPG

### ISSUE THREAD

**Issue by LoicPandul** [DecouvreBitcoin/sovereign-university-data#850]
Verify the authenticity and integrity of a software

The idea is to create a general tutorial explaining how to verify the hash of software and its signature to ensure the downloaded software is safe. This will be useful so we don't have to repeat it every time in tutorials that involve desktop software (Sparrow, Ledger Live, etc.). We'll directly link to this tutorial.

High Priority so we can use it in other tutorials. You can assign it to me. 

@PaoloFoti

**Comment by BitPreto** [comment]
Perfect, then we will change name of the issue once the tuotorial is finished
