### ISSUE TITLE
[TUTORIAL] Ledger Passphrase BIP39

### ISSUE THREAD

**Issue by LoicPandul** [DecouvreBitcoin/sovereign-university-data#856]
I'm working on the Ledger Flex tutorial. It's already very, very long, and I haven't even mentioned the BIP39 passphrase yet. So, I was thinking of doing a separate tutorial where we clearly explain the theoretical workings of the BIP39 passphrase, the risks, etc. There would also be a practical part on how to set up a passphrase on a Ledger, either with the PIN or a standard passphrase.

High Priority.

@PaoloFoti

**Comment by BitPreto** [comment]
Sounds more than good. Will in this new tuto be the direct link to the Ledger Flex tutorial?

**Comment by LoicPandul** [comment]
Yes, but I want to create a single tutorial for all Ledger devices since the process is similar 👍

**Comment by BitPreto** [comment]
Got it, so there will be only one tuto for both ledger flex and ledger nano s, I didn't get that before, I'll update issues. I'll update also this one

**Comment by LoicPandul** [comment]
Here are the tutorials:
- Ledger Flex ;
- Ledger Nano ;
- Passphrase Ledger (for both Flex and Nano) ;)
