### ISSUE TITLE
[TRANSLATION] btc101 - ha

### ISSUE THREAD

**Issue by MariJJhodl** [DecouvreBitcoin/sovereign-university-data#869]
en PBN version: https://planb.network/en/courses/btc101
en github version: https://github.com/PlanB-Network/bitcoin-educational-content/blob/dev/courses/btc101/en.md
ha github version: https://github.com/PlanB-Network/bitcoin-educational-content/blob/Hausa-initial-upload/courses/btc101/ha.md

**Comment by imadangada** [comment]
Bitcoin101 translation to Hausa Language started.

**Comment by MariJJhodl** [comment]
First [proofreading](https://github.com/PlanB-Network/bitcoin-educational-content/pull/1022) done by [Imadangada](https://github.com/imadangada)
