### ISSUE TITLE
[TUTORIAL] Elysium

### ISSUE THREAD

**Issue by BitPreto** [DecouvreBitcoin/sovereign-university-data#906]
Elysisum announced: https://x.com/ElysiumLab_io

Add step-by-step guide to get started with Elysium wallet

**Comment by BitPreto** [comment]
@alevandx this tuto creation is assigned to you :)

**Comment by LoicPandul** [comment]
After consultation with the team, I’m deleting this tutorial because the tool simply no longer exists + delete from github project
