### ISSUE TITLE
[TUTORIAL] Recovery test

### ISSUE THREAD

**Issue by LoicPandul** [DecouvreBitcoin/sovereign-university-data#935]
I would like to create a general tutorial for all software and hardware wallets to show how to perform an empty wallet recovery test to verify the validity of the mnemonic phrase before using a wallet. For each wallet tutorial, we can redirect the reader here to explain how to do it.

High priority

@PaoloFoti

**Comment by BitPreto** [comment]
It is going to be an interesting and useful tuto. Inside which section of the tutorial would you put this one?

**Comment by LoicPandul** [comment]
Mmh I think in the wallet backup section 👍
