### ISSUE TITLE
[TUTORIAL] Passphrase BIP39 (generic explanation)

### ISSUE THREAD

**Issue by BitPreto** [DecouvreBitcoin/sovereign-university-data#951]
This is a new theoretical article to explain what a passphrase is, how it works, and what best practices to follow.

**Comment by BitPreto** [comment]
Hey @LoicPandul , may it be worth adding a "is your passphrase strong enough?" section inside [this tuto](https://planb.network/en/tutorials/wallet/backup/passphrase-a26a0220-806c-44b4-af14-bafdeb1adce7) based on [this trezor article](https://blog.trezor.io/is-your-passphrase-strong-enough-d687f44c63af)?

**Comment by LoicPandul** [comment]
Good idea @PaoloFoti , I’ll add a paragraph thanks!
