### ISSUE TITLE
BTC204 needs to be updated

### ISSUE THREAD

**Issue by MariJJhodl** [DecouvreBitcoin/sovereign-university-data#965]
@LoicPandul BTC204 contains some parts about Coinjoin, and descriptions about Samurai and Wasabi wallet that are out of date. 
SInce you wrote the course, would you like to update it?

@PaoloFoti FYI

**Comment by LoicPandul** [comment]
Hi! I don't necessarily agree. This course was written after the arrest of the founders of Samourai and the announcement of the discontinuation of ZkSNACKs (btw, it’s ZkSNACKs that’s no longer available, not Wasabi). The sections where I discuss coinjoin implementations are meant to explain the different ways of doing coinjoin. Whether those methods are still available or not isn't that important imho, as the goal is to explain. Also, coinjoins with wabisabi are still available. It’s just ZkSNACKs that stopped coordinating, but other coordinators exist. 

As for Whirlpool, it’s indeed unavailable for now, but I think it will be relaunched or another implementation will take the model. A few days ago, there was an announcement about a new wallet that is a fork of SW. It doesn’t have Whirlpool yet, but I believe it will be relaunched in one way or another.

Also, in the course, I’ve included sentences to specify what's available, what’s available in a specific form, and what 's no longer available. I’ll keep it updated over time. ;)

**Comment by MariJJhodl** [comment]
@LoicPandul ok then, thank you for the clarification :)

**Comment by BitPreto** [comment]
I'll also quickly add that we have some tags perfect for these situations. For example, the tag "legacy" is a meta-tag that identifies old procedures and resources not available anymore and thus it would be perfect for some of situations we are currently experiencing. While I don't think we should actively hunt for putting legacy meta-tag on tutorials, we could still put the tag if the need of another edit arises, however without hurry :)
