### ISSUE TITLE
change review chapter title

### ISSUE THREAD

**Issue by mumacadam** [DecouvreBitcoin/sovereign-university-data#970]
![Image](https://github.com/user-attachments/assets/18b0fe7f-dc26-43fb-ae7b-419aab4ebbc3)

Title "Give us some feedback about this course" to change to "Evaluate the course"
And remove "Feedback session"

**Comment by mumacadam** [comment]
it doesn't seem to be done for all courses. here it's BTC204 


![Image](https://github.com/user-attachments/assets/3c669964-0e8e-4104-9bbf-3f239872dbe9)

**Comment by mumacadam** [comment]
still not done @Asi0Flammeus

**Comment by Asi0Flammeus** [comment]
I have fixed the remaining error in btc204
